DECLARE @Jay_Z UNIQUEIDENTIFIER
DECLARE @J_Cole UNIQUEIDENTIFIER
DECLARE @Big_KRIT UNIQUEIDENTIFIER
DECLARE @Nipsey_Hussle UNIQUEIDENTIFIER
DECLARE @Rick_Ross UNIQUEIDENTIFIER
DECLARE @C_Tha_God UNIQUEIDENTIFIER
DECLARE @Little_Brother UNIQUEIDENTIFIER
DECLARE @Rapsody UNIQUEIDENTIFIER

INSERT INTO Quotes
([Quote])
VALUES 
('')